spring:
  application:
    name: reservation-api

  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:reservationdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
